import {h,clear,toast,showMenu,confirm,downloadBlob,safeFileName} from './dom.js';
import {WordFile,PresentationFile,newWord,newPresentation,sheetLibrary,pdfLibrary,zipLibrary,readZip,convertOffice} from './office-core.js';
import {WordEditor} from './wordeditor.js';
import {SheetEditor} from './sheeteditor.js';
import {PresentationEditor} from './presentationeditor.js';
import {PDFEditor} from './pdfeditor.js';
import {navigationSettings,wheelPixels,wheelSpeed} from './navigation.js';

const TYPES=['docx','xlsx','pptx','pdf'],MAX=32*1048576;
const mime={docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',pdf:'application/pdf',csv:'text/csv',rtf:'application/rtf',doc:'application/msword',xls:'application/vnd.ms-excel'};
export class DocumentsPanel {
  constructor(app,host){
    this.app=app;this.host=host;this.current=null;this.zoom=1;this.history=[];this.future=[];this.revision=0;this.queue=Promise.resolve();
    this.bar=h('div.office-bar');this.tools=h('div.office-tools');this.surface=h('div.office-surface');this.scroll=h('div.office-scroll',{tabindex:0,'aria-label':'Área de documentos'},this.surface);
    host.append(this.bar,this.tools,this.scroll);this.renderBar();this.empty();
    this.scroll.addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();this.zoom=Math.min(3,Math.max(.25,this.zoom*Math.exp(-wheelPixels(e)*.0015*wheelSpeed('documents'))));this.surface.style.zoom=String(this.zoom);},{passive:false});
    host.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();e.stopPropagation();}});
    host.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();this.run(()=>this.openFile(e.dataTransfer.files[0]));}});
    document.addEventListener('keydown',e=>{if(!this.visible||e.defaultPrevented||!document.getElementById('overlay')?.hidden)return;const mod=e.ctrlKey||e.metaKey;if(!mod)return;const key=e.key.toLowerCase();if(['s','o'].includes(key)){e.preventDefault();e.stopImmediatePropagation();if(key==='s')this.run(()=>this.save());else this.pick();}else if(['z','y'].includes(key)&&!e.target.closest('input,textarea,[contenteditable]')){e.preventDefault();e.stopImmediatePropagation();this.run(()=>this.undo(key==='y'||e.shiftKey));}});
  }
  report(e){toast(e.message||String(e),'error',8000);}
  async run(fn){if(this.busy)return;this.busy=true;this.host.classList.add('office-busy');try{return await fn();}catch(e){this.report(e);}finally{this.busy=false;this.host.classList.remove('office-busy');}}
  setVisible(v){this.visible=v;}
  empty(){clear(this.surface).append(h('div.office-welcome',h('h2','Documentos'),h('p','Abre, edita y guarda documentos, hojas, presentaciones y PDF.'),h('p.help','DOCX · DOC · RTF · XLSX · XLS · CSV · PPTX · PDF. Arrastra un archivo aquí o usa Abrir. Los formatos DOC y RTF usan el conversor local.'),h('p.help','Cada editor tiene sus propias herramientas. Ctrl+rueda ajusta el zoom; Archivo → Recuperar trabajo conserva tus copias.')));}
  renderBar(){clear(this.bar);const btn=(label,fn)=>h('button.btn.small',{type:'button',on:{click:()=>this.run(fn)}},label);
    const newer=btn('＋ Nuevo',()=>showMenu(TYPES.map(type=>({label:({docx:'Documento de texto',xlsx:'Hoja de cálculo',pptx:'Presentación',pdf:'PDF'}[type]),action:()=>this.run(()=>this.create(type))})),newer));
    this.bar.append(newer,btn('Abrir archivo…',()=>this.pick()));
    if(this.current){const c=this.current;this.name=h('input',{value:c.name,'aria-label':'Nombre del documento',maxlength:120,on:{change:e=>{c.name=e.target.value.trim()||'Documento.'+c.type;this.changed();}}});this.state=h('span.help',c.dirty?'● Cambios pendientes':'Listo');
      const saveAs=btn('Guardar como…',()=>showMenu(this.outputs().map(ext=>({label:ext.toUpperCase(),action:()=>this.run(()=>this.save(ext))})),saveAs));
      this.bar.append(this.name,btn('Guardar',()=>this.save()),saveAs,btn('Deshacer',()=>this.undo(false)),btn('Rehacer',()=>this.undo(true)),this.state);
    }
    this.bar.append(btn('⚙ Rueda',navigationSettings),btn('100 %',()=>{this.zoom=1;this.surface.style.zoom='1';}),btn('⛶ Enfoque',()=>this.app.layout?.toggleFocus()),h('a.btn.small',{href:'../docs/studio-files.html',target:'_blank',rel:'noopener'},'Guía'));
  }
  outputs(){return {docx:['docx','doc','rtf','pdf'],xlsx:['xlsx','xls','csv','pdf'],pptx:['pptx','pdf'],pdf:['pdf']}[this.current.type];}
  pick(){const input=h('input',{type:'file',accept:'.pdf,.docx,.doc,.rtf,.xlsx,.xls,.csv,.pptx,.ugdoc'});input.onchange=()=>{if(input.files[0])this.run(()=>this.openFile(input.files[0]));};input.click();}
  async leave(){if(!this.current?.dirty)return true;await this.app.recovery?.capture('documents');return confirm('Cambiar de documento','Tu trabajo queda en Recuperar trabajo. ¿Quieres abrir el otro documento?','Continuar');}
  async create(type){if(!(await this.leave()))return;let data;if(type==='docx')data=await newWord();else if(type==='pptx')data=await newPresentation();else if(type==='xlsx'){const X=await sheetLibrary(),book=X.utils.book_new();X.utils.book_append_sheet(book,X.utils.aoa_to_sheet([['Nombre','Cantidad','Precio','Total'],['Ejemplo',2,15,{t:'n',f:'B2*C2',v:30}]]),'Hoja 1');data=X.write(book,{type:'array',bookType:'xlsx'});}else {const P=await pdfLibrary(),pdf=await P.PDFDocument.create();pdf.addPage([595.28,841.89]);data=await pdf.save();}
    await this.loadBytes(new Uint8Array(data),type,'Sin título.'+type);this.changed();
  }
  async openFile(file){if(file.size>MAX)throw new Error('El límite por documento es 32 MB.');if(file.name.toLowerCase().endsWith('.ugdoc'))return this.restore(file,{name:file.name});if(!(await this.leave()))return;let type=file.name.split('.').pop().toLowerCase(),bytes=new Uint8Array(await file.arrayBuffer());if(['doc','rtf'].includes(type)){bytes=await convertOffice(bytes,type,'docx');type='docx';}else if(['xls','csv'].includes(type))type='xlsx';else if(!TYPES.includes(type))throw new Error('Formato de documento no admitido');await this.loadBytes(bytes,type,file.name);}
  async loadBytes(bytes,type,name,{history=true,key}={}){
    if(!TYPES.includes(type)||bytes.byteLength>MAX)throw new Error('Documento no admitido o demasiado grande');let model;
    if(type==='docx')model=await WordFile.open(bytes);else if(type==='pptx')model=await PresentationFile.open(bytes);else if(type==='pdf'){const P=await pdfLibrary();model=await P.PDFDocument.load(bytes,{updateMetadata:false});if(model.getPageCount()>1000)throw new Error('El límite es 1000 páginas');}else {this.X=await sheetLibrary();if(bytes[0]===80&&bytes[1]===75)await readZip(bytes);model=this.X.read(bytes,{type:'array',cellStyles:true,cellNF:true,cellDates:false});if(!model.SheetNames.length)throw new Error('El libro no tiene hojas');if(model.SheetNames.length>100||model.SheetNames.reduce((n,s)=>n+Object.keys(model.Sheets[s]).length,0)>300000)throw new Error('El límite es 100 hojas y 300 000 celdas');}
    clearTimeout(this.historyTimer);this.widget?.destroy?.();this.current={type,name,model,dirty:false,recoveryKey:key||'document-'+crypto.randomUUID()};this.revision++;if(history){this.history=[bytes.slice()];this.future=[];}this.renderBar();clear(this.tools);clear(this.surface);const Cls={docx:WordEditor,xlsx:SheetEditor,pptx:PresentationEditor,pdf:PDFEditor}[type];this.widget=type==='xlsx'?new Cls(this,model,this.X,this.surface,this.tools):new Cls(this,model,this.surface,this.tools);this.app.selectTab?.('documents');
  }
  changed(){if(!this.current)return;this.current.dirty=true;this.revision++;if(this.state)this.state.textContent='● Cambios pendientes';this.app.recovery?.schedule('documents');clearTimeout(this.historyTimer);this.historyTimer=setTimeout(()=>this.checkpoint().catch(e=>this.report(e)),450);}
  async bytes(ext=this.current.type){const c=this.current;if(!c)throw new Error('Abre un documento primero');this.widget?.sync?.();if(c.type==='xlsx')return new Uint8Array(this.X.write(c.model,{type:'array',bookType:['xlsx','xls','csv'].includes(ext)?ext:'xlsx',cellStyles:true,sheet:this.widget?.sheet||c.model.SheetNames[0]}));return c.type==='pdf'?c.model.save():c.model.bytes();}
  async checkpoint(){const c=this.current,rev=this.revision;if(!c)return;const bytes=await this.bytes();if(c!==this.current||rev!==this.revision)return;const last=this.history.at(-1);if(last&&last.length===bytes.length&&last.every((v,i)=>v===bytes[i]))return;this.history.push(bytes);this.future=[];while(this.history.length>20||this.history.length>1&&this.history.reduce((n,b)=>n+b.length,0)>64*1048576)this.history.shift();}
  async undo(redo){if(!this.current)return;clearTimeout(this.historyTimer);if(!redo)await this.checkpoint();const c=this.current;if(redo){if(!this.future.length)return;this.history.push(this.future.pop());}else {if(this.history.length<2)return;this.future.push(this.history.pop());}await this.loadBytes(this.history.at(-1),c.type,c.name,{history:false,key:c.recoveryKey});this.current.dirty=true;this.state.textContent='● Cambios pendientes';this.app.recovery?.schedule('documents');}
  async save(ext){if(!this.current)return;const c=this.current,rev=this.revision;ext=ext||c.name.split('.').pop().toLowerCase();if(!this.outputs().includes(ext))ext=c.type;let bytes=await this.bytes(ext);if(ext!==c.type&&!(c.type==='xlsx'&&['xls','csv'].includes(ext)))bytes=await convertOffice(bytes,c.type,ext);downloadBlob(new Blob([bytes],{type:mime[ext]}),safeFileName(c.name.replace(/\.[^.]+$/,''))+'.'+ext);if(ext!=='pdf'&&ext!=='csv'||c.type==='pdf'){if(c===this.current&&rev===this.revision){c.dirty=false;this.state.textContent='Descargado ✓';}}await this.app.recovery?.capture('documents');}
  async snapshot(){const c=this.current;if(!c)return null;const bytes=await this.bytes(),JSZip=await zipLibrary(),zip=new JSZip();zip.file('metadata.json',JSON.stringify({format:'UltraGame Document',version:1,name:c.name,type:c.type}));zip.file('document.bin',bytes);return zip.generateAsync({type:'blob',compression:'DEFLATE'});}
  async restore(blob,row){if(!(await this.leave()))return;const zip=await readZip(await blob.arrayBuffer());const metaFile=zip.file('metadata.json'),data=zip.file('document.bin');if(!metaFile||!data||metaFile._data?.uncompressedSize>16384||data._data?.uncompressedSize>MAX)throw new Error('Copia de documento no válida');const meta=JSON.parse(await metaFile.async('string'));if(meta.format!=='UltraGame Document'||meta.version!==1||!TYPES.includes(meta.type))throw new Error('Copia no compatible');await this.loadBytes(await data.async('uint8array'),meta.type,String(meta.name||row.name).slice(0,120),{key:row.key});this.current.dirty=true;this.state.textContent='● Copia recuperada';}
}
