/* Editores locales. Se conservan las partes OOXML que el usuario no cambia. */
const vendor=new URL('../vendor/',import.meta.url);
const loading=new Map();
export async function library(name,file){if(window[name])return window[name];if(!loading.has(name))loading.set(name,new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL(file,vendor);s.onload=()=>resolve(window[name]);s.onerror=()=>{loading.delete(name);reject(new Error('No se pudo cargar '+name));};document.head.append(s);}));return loading.get(name);}
export const zipLibrary=()=>library('JSZip','jszip.min.js');
export const sheetLibrary=()=>library('XLSX','xlsx.full.min.js');
export const pdfLibrary=()=>library('PDFLib','pdf-lib.min.js');
export async function pdfViewer(){const lib=await import('../vendor/pdf.min.mjs');lib.GlobalWorkerOptions.workerSrc=new URL('pdf.worker.min.mjs',vendor).href;return lib;}
export async function convertOffice(bytes,from,to){const r=await fetch('/api/office/convert?from='+from+'&to='+to,{method:'POST',headers:{'X-UG-Studio':'1'},body:bytes,credentials:'same-origin'});if(!r.ok){let msg='Conversión local no disponible';try{msg=(await r.json()).error||msg;}catch{}throw new Error(msg);}return new Uint8Array(await r.arrayBuffer());}
export const NS={xml:'http://www.w3.org/XML/1998/namespace',w:'http://schemas.openxmlformats.org/wordprocessingml/2006/main',a:'http://schemas.openxmlformats.org/drawingml/2006/main',p:'http://schemas.openxmlformats.org/presentationml/2006/main',r:'http://schemas.openxmlformats.org/officeDocument/2006/relationships',rel:'http://schemas.openxmlformats.org/package/2006/relationships'};
export const all=(node,name)=>Array.from(node.getElementsByTagNameNS('*',name));
export const first=(node,name)=>all(node,name)[0];
export const attr=(node,name,fallback='')=>node?.getAttributeNS(NS.w,name)||node?.getAttribute(name)||fallback;
export const parseXML=text=>{if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('XML con entidades no admitido');const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.getElementsByTagName('parsererror').length)throw new Error('XML dañado');return xml;};
export const xmlText=node=>new XMLSerializer().serializeToString(node);
export function element(xml,prefix,name,attrs={},text){const el=xml.createElementNS(NS[prefix],prefix+':'+name);for(const [k,v]of Object.entries(attrs))el.setAttributeNS(k.includes(':')?NS[k.split(':')[0]]:null,k,String(v));if(text!==undefined)el.textContent=text;return el;}
export async function readZip(bytes){const JSZip=await zipLibrary();const zip=await JSZip.loadAsync(bytes);let total=0,count=0;for(const f of Object.values(zip.files)){if(++count>10000||(total+=f._data?.uncompressedSize||0)>256*1048576)throw new Error('Documento expandido demasiado grande');}return zip;}
export async function xmlPart(zip,path){const f=zip.file(path);if(!f)throw new Error('Falta '+path);const s=await f.async('string');if(s.length>32*1048576)throw new Error('Parte demasiado grande');return parseXML(s);}
export async function relationships(zip,part){const slash=part.lastIndexOf('/'),dir=part.slice(0,slash+1),file=part.slice(slash+1),rel=zip.file(dir+'_rels/'+file+'.rels');const map=new Map();if(rel){const x=parseXML(await rel.async('string'));for(const r of all(x,'Relationship')){if(r.getAttribute('TargetMode')==='External')continue;const target=r.getAttribute('Target')||'';const path=new URL(target,'https://local/'+dir).pathname.slice(1);if(!path.startsWith('../'))map.set(r.getAttribute('Id'),{path,type:r.getAttribute('Type')});}}return map;}
export async function imageData(zip,path){if(!/\.(png|jpe?g|gif|webp)$/i.test(path))return null;const f=zip.file(path);if(!f)return null;const type=/\.jpe?g$/i.test(path)?'jpeg':path.split('.').pop().toLowerCase();return 'data:image/'+type+';base64,'+await f.async('base64');}
function contentTypes(){return '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/></Types>';}
export async function newWord(){const JSZip=await zipLibrary(),z=new JSZip();z.file('[Content_Types].xml',contentTypes().replace('</Types>','<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'));z.file('_rels/.rels','<Relationships xmlns="'+NS.rel+'"><Relationship Id="rId1" Type="'+NS.r+'/officeDocument" Target="word/document.xml"/></Relationships>');z.file('word/document.xml','<w:document xmlns:w="'+NS.w+'" xmlns:r="'+NS.r+'"><w:body><w:p><w:r><w:t>Escribe aquí tu documento.</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>');return z.generateAsync({type:'uint8array'});}
export async function newPresentation(){const JSZip=await zipLibrary(),z=new JSZip();z.file('[Content_Types].xml',contentTypes().replace('</Types>','<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>'));z.file('_rels/.rels','<Relationships xmlns="'+NS.rel+'"><Relationship Id="rId1" Type="'+NS.r+'/officeDocument" Target="ppt/presentation.xml"/></Relationships>');z.file('ppt/presentation.xml','<p:presentation xmlns:p="'+NS.p+'" xmlns:r="'+NS.r+'"><p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst><p:sldSz cx="12192000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>');z.file('ppt/_rels/presentation.xml.rels','<Relationships xmlns="'+NS.rel+'"><Relationship Id="rId1" Type="'+NS.r+'/slide" Target="slides/slide1.xml"/></Relationships>');z.file('ppt/slides/slide1.xml','<p:sld xmlns:p="'+NS.p+'" xmlns:a="'+NS.a+'" xmlns:r="'+NS.r+'"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>');return z.generateAsync({type:'uint8array'});}

export class WordFile {
  static async open(bytes){const d=new WordFile();d.zip=await readZip(bytes);d.xml=await xmlPart(d.zip,'word/document.xml');d.body=first(d.xml,'body');d.rels=await relationships(d.zip,'word/document.xml');d.images=new Map();for(const[id,r]of d.rels)if(r.type.endsWith('/image')){const src=await imageData(d.zip,r.path);if(src)d.images.set(id,src);}return d;}
  async bytes(){this.zip.file('word/document.xml',xmlText(this.xml));return this.zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
  paragraph(text=''){const p=element(this.xml,'w','p');p.append(element(this.xml,'w','r',{},undefined));p.lastChild.append(element(this.xml,'w','t',{},text));return p;}
  appendParagraph(text=''){const p=this.paragraph(text);this.body.insertBefore(p,[...this.body.children].find(n=>n.localName==='sectPr')||null);return p;}
  setParagraph(p,runs,align){
    let pr=[...p.children].find(n=>n.localName==='pPr');for(const c of [...p.childNodes])if(c!==pr)p.removeChild(c);
    if(align){if(!pr){pr=element(this.xml,'w','pPr');p.prepend(pr);}let jc=first(pr,'jc');if(!jc){jc=element(this.xml,'w','jc');pr.append(jc);}jc.setAttributeNS(NS.w,'w:val',align);}
    for(const run of runs){if(run.drawing){p.append(run.drawing.cloneNode(true));continue;}const r=element(this.xml,'w','r'),rp=element(this.xml,'w','rPr');if(run.bold)rp.append(element(this.xml,'w','b'));if(run.italic)rp.append(element(this.xml,'w','i'));if(run.strike)rp.append(element(this.xml,'w','strike'));if(run.underline)rp.append(element(this.xml,'w','u',{'w:val':'single'}));if(run.color&&/^#[0-9a-f]{6}$/i.test(run.color))rp.append(element(this.xml,'w','color',{'w:val':run.color.slice(1)}));if(run.size)rp.append(element(this.xml,'w','sz',{'w:val':Math.round(Math.min(200,Math.max(6,run.size))*2)}));r.append(rp);run.text.split('\n').forEach((s,i)=>{if(i)r.append(element(this.xml,'w','br'));r.append(element(this.xml,'w','t',{'xml:space':'preserve'},s));});p.append(r);}
  }
  addTable(rows,cols){rows=Math.max(1,Math.min(40,rows));cols=Math.max(1,Math.min(20,cols));const t=element(this.xml,'w','tbl'),pr=element(this.xml,'w','tblPr'),b=element(this.xml,'w','tblBorders');for(const side of ['top','left','bottom','right','insideH','insideV'])b.append(element(this.xml,'w',side,{'w:val':'single','w:sz':4,'w:color':'aaaaaa'}));pr.append(b);t.append(pr);for(let y=0;y<rows;y++){const tr=element(this.xml,'w','tr');for(let x=0;x<cols;x++){const td=element(this.xml,'w','tc');td.append(this.paragraph(''));tr.append(td);}t.append(tr);}this.body.insertBefore(t,[...this.body.children].find(n=>n.localName==='sectPr')||null);}
}

export class PresentationFile {
  static async open(bytes){const d=new PresentationFile();d.zip=await readZip(bytes);d.xml=await xmlPart(d.zip,'ppt/presentation.xml');const size=first(d.xml,'sldSz');d.width=+(size?.getAttribute('cx')||12192000)/9525;d.height=+(size?.getAttribute('cy')||6858000)/9525;const rels=await relationships(d.zip,'ppt/presentation.xml');d.slides=[];for(const node of all(d.xml,'sldId')){const rel=rels.get(node.getAttributeNS(NS.r,'id'));if(!rel)continue;const xml=await xmlPart(d.zip,rel.path),images=new Map();for(const[id,r]of await relationships(d.zip,rel.path))if(r.type.endsWith('/image')){const src=await imageData(d.zip,r.path);if(src)images.set(id,src);}d.slides.push({xml,path:rel.path,node,images});}if(!d.slides.length)throw new Error('La presentación no tiene diapositivas');return d;}
  shapes(i){const s=this.slides[i];return [...first(s.xml,'spTree').children].filter(n=>['sp','pic','graphicFrame'].includes(n.localName));}
  bounds(shape){const t=first(shape,'xfrm'),o=t&&first(t,'off'),e=t&&first(t,'ext');return{x:+(o?.getAttribute('x')||0)/9525,y:+(o?.getAttribute('y')||0)/9525,w:+(e?.getAttribute('cx')||1905000)/9525,h:+(e?.getAttribute('cy')||571500)/9525};}
  setBounds(shape,b){let xfrm=first(shape,'xfrm');if(!xfrm){const pr=first(shape,'spPr');if(!pr)return;xfrm=element(shape.ownerDocument,'a','xfrm');pr.prepend(xfrm);}let off=first(xfrm,'off'),ext=first(xfrm,'ext');if(!off){off=element(shape.ownerDocument,'a','off');xfrm.append(off);}if(!ext){ext=element(shape.ownerDocument,'a','ext');xfrm.append(ext);}off.setAttribute('x',Math.round(b.x*9525));off.setAttribute('y',Math.round(b.y*9525));ext.setAttribute('cx',Math.round(Math.max(1,b.w)*9525));ext.setAttribute('cy',Math.round(Math.max(1,b.h)*9525));}
  setText(shape,text){const doc=shape.ownerDocument;let body=first(shape,'txBody');if(!body)return;let style=first(body,'rPr')?.cloneNode(true);for(const p of [...body.children])if(p.localName==='p')p.remove();for(const line of text.split('\n')){const p=element(doc,'a','p'),r=element(doc,'a','r');if(style)r.append(style.cloneNode(true));r.append(element(doc,'a','t',{},line));p.append(r);body.append(p);}}
  addShape(i,kind='text'){const s=this.slides[i],d=s.xml,shape=element(d,'p','sp'),nv=element(d,'p','nvSpPr');const max=Math.max(1,...all(d,'cNvPr').map(n=>+n.getAttribute('id')||0));nv.append(element(d,'p','cNvPr',{id:max+1,name:kind==='text'?'Texto':'Forma'}),element(d,'p','cNvSpPr'),element(d,'p','nvPr'));shape.append(nv);const pr=element(d,'p','spPr'),geom=element(d,'a','prstGeom',{prst:kind==='ellipse'?'ellipse':'rect'});geom.append(element(d,'a','avLst'));pr.append(element(d,'a','xfrm'),geom);if(kind!=='text'){const fill=element(d,'a','solidFill');fill.append(element(d,'a','srgbClr',{val:'7185F5'}));pr.append(fill);}else pr.append(element(d,'a','noFill'));shape.append(pr);const body=element(d,'p','txBody');body.append(element(d,'a','bodyPr'),element(d,'a','lstStyle'));shape.append(body);first(d,'spTree').append(shape);this.setBounds(shape,{x:80,y:80,w:300,h:100});this.setText(shape,kind==='text'?'Escribe tu texto':'');return shape;}
  async duplicateSlide(i){const source=this.slides[i];let n=1;while(this.zip.file('ppt/slides/slide'+n+'.xml'))n++;const path='ppt/slides/slide'+n+'.xml',slide={...source,path,xml:parseXML(xmlText(source.xml))};this.zip.file(path,xmlText(slide.xml));const srcRels=this.zip.file(source.path.replace('/slides/','/slides/_rels/')+'.rels');if(srcRels)this.zip.file(path.replace('/slides/','/slides/_rels/')+'.rels',await srcRels.async('uint8array'));const rels=await xmlPart(this.zip,'ppt/_rels/presentation.xml.rels'),id='rIdStudio'+crypto.randomUUID().replaceAll('-','');const rel=rels.createElementNS(NS.rel,'Relationship');rel.setAttribute('Id',id);rel.setAttribute('Type',NS.r+'/slide');rel.setAttribute('Target','slides/slide'+n+'.xml');rels.documentElement.append(rel);this.zip.file('ppt/_rels/presentation.xml.rels',xmlText(rels));slide.node=element(this.xml,'p','sldId',{id:Math.max(255,...all(this.xml,'sldId').map(n=>+n.getAttribute('id')))+1,'r:id':id});source.node.after(slide.node);this.slides.splice(i+1,0,slide);const types=await xmlPart(this.zip,'[Content_Types].xml'),over=types.createElementNS(types.documentElement.namespaceURI,'Override');over.setAttribute('PartName','/'+path);over.setAttribute('ContentType','application/vnd.openxmlformats-officedocument.presentationml.slide+xml');types.documentElement.append(over);this.zip.file('[Content_Types].xml',xmlText(types));return i+1;}
  async bytes(){this.zip.file('ppt/presentation.xml',xmlText(this.xml));for(const s of this.slides)this.zip.file(s.path,xmlText(s.xml));return this.zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
}

// Fórmulas comunes sin eval/new Function. Las no soportadas mantienen su fórmula al guardar.
export function recalculate(book,XLSX){const cache=new Map(),active=new Set();let budget=30000;
  const calc=(sheet,address)=>{const id=sheet+'!'+address;if(cache.has(id))return cache.get(id);if(active.has(id))throw new Error('#CICLO!');if(--budget<0)throw new Error('#LÍMITE!');const cell=book.Sheets[sheet]?.[address];if(!cell)return 0;if(!cell.f)return typeof cell.v==='number'?cell.v:Number(cell.v)||0;active.add(id);try{const v=formula(cell.f,sheet);if(Number.isFinite(v)||typeof v==='boolean'){cell.v=Number(v);cell.t='n';delete cell.w;}cache.set(id,cell.v||0);return cell.v||0;}finally{active.delete(id);}};
  function formula(source,sheet){const tokens=source.match(/\s*(?:\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|\$?[A-Za-z]+\$?\d+|[A-Za-z_][A-Za-z_0-9]*|<=|>=|<>|[+\-*/^(),:;=<>%])/g)||[];if(tokens.join('').replace(/\s/g,'')!==source.replace(/\s/g,''))throw new Error('#FÓRMULA!');const t=tokens.map(x=>x.trim().toUpperCase());let i=0;
    const expression=(min=0)=>{let x,token=t[i++];if(token==='+'||token==='-')x=(token==='-'?-1:1)*expression(4);else if(token==='('){x=expression();if(t[i++]!==')')throw new Error('#FÓRMULA!');}else if(/^\d/.test(token||''))x=Number(token);else if(/^\$?[A-Z]+\$?\d+$/.test(token||'')){const a=token.replaceAll('$','');if(t[i]===':'){i++;const end=t[i++].replaceAll('$',''),r=XLSX.utils.decode_range(a+':'+end);if((r.e.r-r.s.r+1)*(r.e.c-r.s.c+1)>10000)throw new Error('#LÍMITE!');x=[];for(let row=r.s.r;row<=r.e.r;row++)for(let col=r.s.c;col<=r.e.c;col++)x.push(calc(sheet,XLSX.utils.encode_cell({r:row,c:col})));}else x=calc(sheet,a);}else if(t[i]==='('){i++;const args=[];if(t[i]!==')')do{args.push(expression());if(![',',';'].includes(t[i]))break;i++;}while(i<t.length);if(t[i++]!==')')throw new Error('#FÓRMULA!');const flat=args.flat();switch(token){case'SUM':case'SUMA':x=flat.reduce((a,b)=>a+b,0);break;case'AVERAGE':case'PROMEDIO':x=flat.reduce((a,b)=>a+b,0)/flat.length;break;case'MIN':x=Math.min(...flat);break;case'MAX':x=Math.max(...flat);break;case'COUNT':case'CONTAR':x=flat.length;break;case'IF':case'SI':x=args[0]?args[1]:args[2];break;case'ROUND':case'REDONDEAR':x=Math.round(args[0]*10**(args[1]||0))/10**(args[1]||0);break;case'ABS':x=Math.abs(args[0]);break;default:throw new Error('#NO SOPORTADA');}}else throw new Error('#FÓRMULA!');
      if(t[i]==='%'){i++;x/=100;}const precedence={'=':1,'<>':1,'<':1,'>':1,'<=':1,'>=':1,'+':2,'-':2,'*':3,'/':3,'^':4};while((precedence[t[i]]||0)>min){const op=t[i++],y=expression(precedence[op]-(op==='^'?1:0));if(Array.isArray(x)||Array.isArray(y))throw new Error('#VALOR!');x=op==='+'?x+y:op==='-'?x-y:op==='*'?x*y:op==='/'?x/y:op==='^'?x**y:op==='='?x===y:op==='<>'?x!==y:op==='<'?x<y:op==='>'?x>y:op==='<='?x<=y:x>=y;}return x;};const result=expression();if(i!==t.length)throw new Error('#FÓRMULA!');return result;
  }
  const errors=[];for(const sheet of book.SheetNames)for(const [a,c]of Object.entries(book.Sheets[sheet]))if(c?.f)try{calc(sheet,a);}catch(e){errors.push(sheet+'!'+a+': '+e.message);}return errors;
}
