import {NS,parseXML,xmlText,xmlPart,first,element} from './office-core.js';
export async function insertOfficeImage(model,file,slideIndex){
  if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)||file.size>16*1048576)throw new Error('Usa una imagen PNG, JPG, WebP o GIF de hasta 16 MB');
  const image=await createImageBitmap(file);if(image.width*image.height>32*1048576){image.close();throw new Error('La imagen supera 32 megapíxeles');}
  const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);image.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png')),bytes=new Uint8Array(await blob.arrayBuffer());
  const id='rIdStudio'+crypto.randomUUID().replaceAll('-',''),filename=id+'.png',isSlide=slideIndex!==undefined,dir=isSlide?'ppt':'word',part=isSlide?model.slides[slideIndex].path:'word/document.xml',slash=part.lastIndexOf('/'),relPath=part.slice(0,slash+1)+'_rels/'+part.slice(slash+1)+'.rels';
  const rels=model.zip.file(relPath)?await xmlPart(model.zip,relPath):parseXML('<Relationships xmlns="'+NS.rel+'"/>');const rel=rels.createElementNS(NS.rel,'Relationship');rel.setAttribute('Id',id);rel.setAttribute('Type',NS.r+'/image');rel.setAttribute('Target',(isSlide?'../':'')+'media/'+filename);rels.documentElement.append(rel);model.zip.file(relPath,xmlText(rels));model.zip.file(dir+'/media/'+filename,bytes);
  const ct=await xmlPart(model.zip,'[Content_Types].xml');if(![...ct.documentElement.children].some(e=>e.getAttribute('Extension')==='png')){const n=ct.createElementNS(ct.documentElement.namespaceURI,'Default');n.setAttribute('Extension','png');n.setAttribute('ContentType','image/png');ct.documentElement.append(n);model.zip.file('[Content_Types].xml',xmlText(ct));}
  const width=Math.min(isSlide?600:600,canvas.width),height=canvas.height*width/canvas.width,cx=Math.round(width*9525),cy=Math.round(height*9525),source=canvas.toDataURL('image/png');
  const picture='<pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="Imagen"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="'+id+'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+cx+'" cy="'+cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic>';
  if(isSlide){const slide=model.slides[slideIndex],node=parseXML('<p:pic xmlns:p="'+NS.p+'" xmlns:a="'+NS.a+'" xmlns:r="'+NS.r+'"><p:nvPicPr><p:cNvPr id="'+(Date.now()%1000000000)+'" name="Imagen"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="'+id+'"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+cx+'" cy="'+cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>').documentElement;const shape=slide.xml.importNode(node,true);first(slide.xml,'spTree').append(shape);slide.images.set(id,source);return shape;}
  const node=parseXML('<w:r xmlns:w="'+NS.w+'" xmlns:a="'+NS.a+'" xmlns:r="'+NS.r+'" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><w:drawing><wp:inline><wp:extent cx="'+cx+'" cy="'+cy+'"/><wp:docPr id="'+(Date.now()%1000000000)+'" name="Imagen"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">'+picture+'</a:graphicData></a:graphic></wp:inline></w:drawing></w:r>').documentElement;
  const p=model.appendParagraph('');p.replaceChildren(model.xml.importNode(node,true));model.images.set(id,source);return p;
}
export function imagePicker(owner,callback){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif';input.onchange=()=>{if(input.files[0])owner.run(()=>callback(input.files[0]));};input.click();}
