import {h,clear,dialog,toast} from './dom.js';
import {pdfViewer,pdfLibrary} from './office-core.js';
export class PDFEditor {
  constructor(owner,model,host,toolbar){this.owner=owner;this.model=model;this.host=host;this.page=0;this.tool='text';this.color='#ef4444';this.size=16;this.renderId=0;
    this.pages=h('select',{'aria-label':'Página PDF',on:{change:e=>{this.page=+e.target.value;this.ready=this.render();}}});
    toolbar.append(this.pages,...[['Texto','text'],['Resaltar','highlight'],['Rectángulo','rect'],['Lápiz','pen']].map(([t,id])=>h('button.btn.small',{on:{click:()=>{this.tool=id;toast('PDF: '+t);}}},t)),h('input',{type:'color',value:this.color,'aria-label':'Color de anotación',on:{input:e=>this.color=e.target.value}}),h('input',{type:'number',min:6,max:100,value:16,'aria-label':'Tamaño de texto PDF',on:{change:e=>this.size=Math.max(6,Math.min(100,+e.target.value||16))}}),h('button.btn.small',{on:{click:async()=>{const p=model.getPage(this.page);const lib=await pdfLibrary();p.setRotation(lib.degrees((p.getRotation().angle+90)%360));owner.changed();this.ready=this.render();}}},'Girar 90°'),h('button.btn.small',{on:{click:()=>{model.addPage();this.page=model.getPageCount()-1;owner.changed();this.ready=this.render();}}},'＋ Página'),h('button.btn.small',{on:{click:()=>{if(model.getPageCount()>1){model.removePage(this.page);this.page=Math.min(this.page,model.getPageCount()-1);owner.changed();this.ready=this.render();}}}},'Borrar página'),h('button.btn.small',{on:{click:()=>this.forms()}},'Campos del formulario'));
    this.ready=this.render();
  }
  async render(){try{return await this.renderPage();}catch(e){this.owner.report(e);}}
  async renderPage(){const id=++this.renderId;clear(this.host);clear(this.pages);for(let i=0;i<this.model.getPageCount();i++)this.pages.append(h('option',{value:i,selected:i===this.page},'Página '+(i+1)));const viewer=await pdfViewer(),bytes=await this.model.save(),loading=viewer.getDocument({data:bytes,isEvalSupported:false});const pdf=await loading.promise;try{const page=await pdf.getPage(this.page+1),viewport=page.getViewport({scale:1.25});if(id!==this.renderId)return;const canvas=h('canvas.office-pdf',{width:Math.ceil(viewport.width),height:Math.ceil(viewport.height),'aria-label':'Página PDF editable'});this.host.append(h('p.help','El contenido original se conserva. Añade texto, resaltados y trazos sobre la página; los cambios se guardan en el PDF.'),canvas);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;
      canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const point=ev=>{const r=canvas.getBoundingClientRect();return viewport.convertToPdfPoint((ev.clientX-r.left)*canvas.width/r.width,(ev.clientY-r.top)*canvas.height/r.height);};const start=point(e),points=[start];const move=ev=>{points.push(point(ev));};const up=async ev=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);const end=point(ev);try{await this.annotate(start,end,points);this.owner.changed();this.ready=this.render();}catch(err){toast(err.message,'error');}};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up,{once:true});canvas.addEventListener('pointercancel',()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);},{once:true});};
    }finally{await pdf.destroy();}}
  async annotate(a,b,points){const lib=await pdfLibrary(),p=this.model.getPage(this.page),color=lib.rgb(parseInt(this.color.slice(1,3),16)/255,parseInt(this.color.slice(3,5),16)/255,parseInt(this.color.slice(5,7),16)/255);
    if(this.tool==='text'){let input;const ok=await dialog('Añadir texto al PDF',body=>{input=h('textarea',{rows:4,'aria-label':'Texto PDF',placeholder:'Escribe aquí'});body.append(input);},[{label:'Cancelar',value:false},{label:'Añadir',value:true,kind:'primary'}]);if(!ok||!input.value)return;const font=await this.model.embedFont(lib.StandardFonts.Helvetica);p.drawText(input.value,{x:a[0],y:a[1],size:this.size,color,font,lineHeight:this.size*1.25});}
    else if(this.tool==='pen'){for(let i=1;i<points.length;i++)p.drawLine({start:{x:points[i-1][0],y:points[i-1][1]},end:{x:points[i][0],y:points[i][1]},thickness:2,color});}
    else{const options={x:Math.min(a[0],b[0]),y:Math.min(a[1],b[1]),width:Math.max(1,Math.abs(a[0]-b[0])),height:Math.max(1,Math.abs(a[1]-b[1]))};if(this.tool==='highlight')p.drawRectangle({...options,color,opacity:.3});else p.drawRectangle({...options,borderColor:color,borderWidth:2});}}
  async forms(){const fields=this.model.getForm().getFields(),changes=[];if(!fields.length){toast('Este PDF no contiene campos de formulario.','warn');return;}const ok=await dialog('Rellenar formulario PDF',body=>{for(const field of fields){let input;if(field.getText){input=h('input',{value:field.getText()||'','aria-label':field.getName()});changes.push(()=>field.setText(input.value));}else if(field.isChecked){input=h('input',{type:'checkbox',checked:field.isChecked(),'aria-label':field.getName()});changes.push(()=>input.checked?field.check():field.uncheck());}else if(field.getOptions){input=h('select',{'aria-label':field.getName()},field.getOptions().map(v=>h('option',{value:v,selected:field.getSelected?.().includes(v)},v)));changes.push(()=>field.select(input.value));}if(input)body.append(h('div.field',h('label',field.getName()),input));}},[{label:'Cancelar',value:false},{label:'Aplicar',value:true,kind:'primary'}]);if(ok){changes.forEach(fn=>fn());this.owner.changed();this.ready=this.render();}}
  destroy(){this.renderId++;}
}
