import {h,clear} from './dom.js';
import {first,all,element} from './office-core.js';
import {insertOfficeImage,imagePicker} from './office-images.js';
export class PresentationEditor {
  constructor(owner,model,host,toolbar){this.owner=owner;this.model=model;this.host=host;this.slide=0;this.selected=null;
    this.pages=h('select',{'aria-label':'Diapositiva',on:{change:e=>{this.slide=+e.target.value;this.selected=null;this.render();}}});
    toolbar.append(this.pages,...[['Texto','text'],['Rectángulo','rect'],['Elipse','ellipse']].map(([label,type])=>h('button.btn.small',{on:{click:()=>{this.selected=model.addShape(this.slide,type);this.render();owner.changed();}}},'＋ '+label)),h('button.btn.small',{on:{click:async()=>{this.slide=await model.duplicateSlide(this.slide);this.selected=null;this.render();owner.changed();}}},'Duplicar diapositiva'),h('button.btn.small',{on:{click:()=>{if(model.slides.length<=1)return;model.slides[this.slide].node.remove();model.slides.splice(this.slide,1);this.slide=Math.max(0,this.slide-1);this.selected=null;this.render();owner.changed();}}},'Borrar diapositiva'));
    toolbar.append(h('button.btn.small',{on:{click:()=>imagePicker(owner,async file=>{this.selected=await insertOfficeImage(model,file,this.slide);this.render();owner.changed();})}},'＋ Imagen'));
    this.render();
  }
  render(){clear(this.host);clear(this.pages);this.model.slides.forEach((s,i)=>this.pages.append(h('option',{value:i,selected:i===this.slide},'Diapositiva '+(i+1))));const layout=h('div.office-slide-layout'),stage=h('div.office-slide',{style:{width:this.model.width+'px',height:this.model.height+'px'},'aria-label':'Diapositiva editable'});this.stage=stage;
    const slide=this.model.slides[this.slide];const bg=first(first(slide.xml,'bg')||slide.xml.createElement('empty'),'srgbClr')?.getAttribute('val');if(/^[a-f0-9]{6}$/i.test(bg||''))stage.style.background='#'+bg;
    for(const shape of this.model.shapes(this.slide)){
      const b=this.model.bounds(shape),text=all(shape,'p').map(p=>all(p,'t').map(t=>t.textContent).join('')).join('\n'),node=h('div.office-shape',{tabindex:'0',role:'button','aria-label':text?'Objeto: '+text.slice(0,60):'Forma de diapositiva',class:this.selected===shape?'selected':null,style:{left:b.x+'px',top:b.y+'px',width:b.w+'px',height:b.h+'px'}});
      const pr=first(shape,'spPr'),fill=pr&&first(pr,'solidFill'),color=fill&&first(fill,'srgbClr')?.getAttribute('val');if(/^[a-f0-9]{6}$/i.test(color||''))node.style.background='#'+color;if(first(shape,'prstGeom')?.getAttribute('prst')==='ellipse')node.style.borderRadius='50%';
      const r=first(shape,'rPr');node.style.fontSize=(+(r?.getAttribute('sz')||2400)/100)+'pt';if(r?.getAttribute('b')==='1')node.style.fontWeight='bold';const tc=r&&first(r,'srgbClr')?.getAttribute('val');node.style.color=/^[a-f0-9]{6}$/i.test(tc||'')?'#'+tc:'#202634';
      const src=slide.images.get(first(shape,'blip')?.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','embed'));if(src)node.append(h('img',{src,alt:'Imagen de diapositiva',draggable:false}));else node.textContent=text;
      node.onclick=()=>{this.selected=shape;this.renderProps();stage.querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');};node.onkeydown=e=>{e.stopPropagation();if(e.key==='Delete'){this.selected=shape;this.remove();}else if(e.key==='Enter'){this.selected=shape;this.renderProps();this.props.querySelector('textarea')?.focus();}};
      node.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();this.selected=shape;this.renderProps();stage.querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');node.setPointerCapture(e.pointerId);const start=this.model.bounds(shape),x=e.clientX,y=e.clientY,scale=stage.getBoundingClientRect().width/this.model.width;
        const move=ev=>{const b={...start,x:Math.round(start.x+(ev.clientX-x)/scale),y:Math.round(start.y+(ev.clientY-y)/scale)};this.model.setBounds(shape,b);node.style.left=b.x+'px';node.style.top=b.y+'px';};const done=ev=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',done);node.removeEventListener('pointercancel',cancel);this.renderProps();this.owner.changed();};const cancel=()=>{this.model.setBounds(shape,start);done();this.render();};node.addEventListener('pointermove',move);node.addEventListener('pointerup',done);node.addEventListener('pointercancel',cancel);
      };stage.append(node);
    }
    this.props=h('div.office-shape-props');layout.append(stage,this.props);this.host.append(layout);this.renderProps();
  }
  renderProps(){clear(this.props);if(!this.selected){this.props.append(h('p.help','Selecciona un objeto para editar su texto, color, posición y tamaño. Arrastra para moverlo.'));return;}
    const shape=this.selected,b=this.model.bounds(shape);this.props.append(h('b','Propiedades del objeto'));
    for(const [key,label]of [['x','X'],['y','Y'],['w','Ancho'],['h','Alto']])this.props.append(h('label',label,h('input',{type:'number',value:Math.round(b[key]),min:key==='w'||key==='h'?1:-10000,max:20000,'aria-label':label+' del objeto',on:{change:e=>{b[key]=Math.max(key==='w'||key==='h'?1:-10000,Math.min(20000,+e.target.value||1));this.model.setBounds(shape,b);this.render();this.owner.changed();}}})));
    if(first(shape,'txBody'))this.props.append(h('label','Texto',h('textarea',{rows:5,'aria-label':'Texto del objeto',value:all(shape,'p').map(p=>all(p,'t').map(t=>t.textContent).join('')).join('\n'),on:{input:e=>{this.model.setText(shape,e.target.value);const selected=this.stage.querySelector('.selected');if(selected)selected.textContent=e.target.value;this.owner.changed();}}})));
    const style=(kind,v)=>{const d=shape.ownerDocument;if(kind==='fill'){const pr=first(shape,'spPr');if(!pr)return;[...pr.children].filter(n=>['noFill','solidFill'].includes(n.localName)).forEach(n=>n.remove());const fill=element(d,'a','solidFill');fill.append(element(d,'a','srgbClr',{val:v.slice(1)}));pr.append(fill);}else for(const r of all(shape,'r')){let rp=first(r,'rPr');if(!rp){rp=element(d,'a','rPr');r.prepend(rp);}if(kind==='size')rp.setAttribute('sz',Math.max(600,Math.min(20000,v*100)));else{all(rp,'solidFill').forEach(n=>n.remove());const f=element(d,'a','solidFill');f.append(element(d,'a','srgbClr',{val:v.slice(1)}));rp.append(f);}}this.render();this.owner.changed();};
    this.props.append(h('label','Relleno',h('input',{type:'color',value:'#7185f5','aria-label':'Relleno de forma',on:{change:e=>style('fill',e.target.value)}})),h('label','Color de texto',h('input',{type:'color',value:'#202634','aria-label':'Color de texto',on:{change:e=>style('text',e.target.value)}})),h('label','Tamaño (pt)',h('input',{type:'number',min:6,max:200,value:+(first(shape,'rPr')?.getAttribute('sz')||2400)/100,on:{change:e=>style('size',+e.target.value)}})),h('button.btn.small',{on:{click:()=>{shape.parentNode.append(shape);this.render();this.owner.changed();}}},'Traer al frente'),h('button.btn.small',{on:{click:()=>this.remove()}},'Borrar objeto'));
  }
  remove(){if(this.selected){this.selected.remove();this.selected=null;this.render();this.owner.changed();}}
}
