import {h,clear,dialog,toast} from './dom.js';
import {recalculate} from './office-core.js';
export class SheetEditor {
  constructor(owner,book,XLSX,host,toolbar){this.owner=owner;this.book=book;this.X=XLSX;this.host=host;this.sheet=book.SheetNames[0];this.start=0;this.rows=60;this.cols=20;this.address='A1';
    this.selector=h('select',{'aria-label':'Hoja del libro',on:{change:e=>{this.sheet=e.target.value;this.start=0;this.render();}}});this.refreshTabs();
    this.addr=h('input',{value:'A1','aria-label':'Dirección de celda',style:{width:'85px'},on:{change:()=>{if(/^[A-Z]{1,3}[1-9]\d{0,6}$/i.test(this.addr.value)){this.address=this.addr.value.toUpperCase();this.start=Math.floor(this.X.utils.decode_cell(this.address).r/this.rows)*this.rows;this.cols=Math.min(200,Math.max(this.cols,this.X.utils.decode_cell(this.address).c+1));this.render();this.select(this.address);}}}});
    this.formula=h('input',{'aria-label':'Valor o fórmula de celda',placeholder:'Valor o =SUM(A1:A5)',style:{minWidth:'220px',flex:'1'},on:{keydown:e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();this.setCell(this.address,this.formula.value);this.render();}},change:()=>{this.setCell(this.address,this.formula.value);this.render();}}});
    toolbar.append(this.selector,h('button.btn.small',{on:{click:()=>this.addSheet()}},'＋ Hoja'),this.addr,this.formula,h('button.btn.small',{on:{click:()=>{this.start=Math.max(0,this.start-this.rows);this.render();}}},'↑ Filas'),h('button.btn.small',{on:{click:()=>{this.start+=this.rows;this.render();}}},'↓ Filas'),h('button.btn.small',{on:{click:()=>this.sort()}},'Ordenar A→Z'),h('button.btn.small',{on:{click:()=>{this.cols=Math.min(200,this.cols+20);this.render();}}},'＋ Columnas'));
    toolbar.append(h('select',{'aria-label':'Formato numérico',on:{change:e=>{const c=this.book.Sheets[this.sheet][this.address];if(c){c.z=e.target.value;delete c.w;this.render();owner.changed();}}}},[['General','General'],['0','Entero'],['0.00','Decimal'],['0.00%','Porcentaje'],['$#,##0.00','Moneda'],['yyyy-mm-dd','Fecha']].map(([v,t])=>h('option',{value:v},t))));
    this.render();
  }
  refreshTabs(){clear(this.selector);this.book.SheetNames.forEach(n=>this.selector.append(h('option',{value:n,selected:n===this.sheet},n)));}
  select(address){this.address=address;this.addr.value=address;const c=this.book.Sheets[this.sheet][address];this.formula.value=c?.f?'='+c.f:c?.v===undefined?'':String(c.v);this.host.querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));this.host.querySelector('[data-cell="'+address+'"]')?.classList.add('selected');}
  setCell(address,value,defer=false){const ws=this.book.Sheets[this.sheet];const existing=ws[address]||{};if(value==='')delete ws[address];else{const c={...existing};delete c.w;delete c.f;delete c.h;delete c.r;if(value[0]==='='){c.f=value.slice(1);c.t='n';c.v=0;}else if(value[0]==="'"){c.t='s';c.v=value.slice(1);}else if(/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(value)&&Number.isFinite(+value)){c.t='n';c.v=+value;}else{c.t='s';c.v=value;}ws[address]=c;}const pos=this.X.utils.decode_cell(address),range=this.X.utils.decode_range(ws['!ref']||'A1');range.e.r=Math.max(range.e.r,pos.r);range.e.c=Math.max(range.e.c,pos.c);ws['!ref']=this.X.utils.encode_range(range);if(!defer){this.errors=recalculate(this.book,this.X);this.owner.changed();}}
  render(){clear(this.host);const ws=this.book.Sheets[this.sheet],table=h('table.office-sheet'),head=h('tr',h('th','#'));
    for(let c=0;c<this.cols;c++)head.append(h('th',this.X.utils.encode_col(c)));table.append(h('thead',head));const body=h('tbody');
    for(let r=this.start;r<this.start+this.rows;r++){const row=h('tr',h('th',String(r+1)));for(let c=0;c<this.cols;c++){const address=this.X.utils.encode_cell({r,c}),cell=ws[address],td=h('td',{tabindex:'0',dataset:{cell:address},title:cell?.f?'='+cell.f:address},cell?this.X.utils.format_cell(cell):'');td.onclick=()=>this.select(address);td.ondblclick=()=>this.edit(td,address);td.onkeydown=e=>{e.stopPropagation();if(e.key==='Enter'||e.key==='F2'){e.preventDefault();this.edit(td,address);}else if(e.key==='Delete'){this.setCell(address,'');this.render();}else if(e.key.startsWith('Arrow')){e.preventDefault();const delta={ArrowLeft:[0,-1],ArrowRight:[0,1],ArrowUp:[-1,0],ArrowDown:[1,0]}[e.key],rr=Math.max(0,r+delta[0]),cc=Math.max(0,c+delta[1]);this.select(this.X.utils.encode_cell({r:rr,c:cc}));this.host.querySelector('[data-cell="'+this.address+'"]')?.focus();}};td.onpaste=e=>{e.preventDefault();const lines=e.clipboardData.getData('text/plain').replace(/\r/g,'').split('\n').slice(0,1000);for(let y=0;y<lines.length;y++)lines[y].split('\t').slice(0,200).forEach((v,x)=>this.setCell(this.X.utils.encode_cell({r:r+y,c:c+x}),v,true));this.errors=recalculate(this.book,this.X);this.owner.changed();this.render();};row.append(td);}body.append(row);}table.append(body);this.host.append(h('p.help','Doble clic o F2 para editar · Enter confirma · pega filas desde una hoja · '+(this.errors?.length?'Fórmulas pendientes: '+this.errors.slice(0,3).join(' · '):'Fórmulas comunes: SUM, AVERAGE, MIN, MAX, COUNT, IF, ROUND y ABS.')),table);this.select(this.address);}
  edit(td,address){const c=this.book.Sheets[this.sheet][address],input=h('input',{'aria-label':'Editar '+address,value:c?.f?'='+c.f:String(c?.v??'')});clear(td).append(input);input.focus();input.select();let committed=false;const commit=()=>{if(committed)return;committed=true;this.setCell(address,input.value);this.render();};input.onkeydown=e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();commit();}else if(e.key==='Escape'){committed=true;this.render();}};input.onblur=commit;}
  async addSheet(){let input;const ok=await dialog('Nueva hoja',b=>{input=h('input',{value:'Hoja '+(this.book.SheetNames.length+1),maxlength:31,'aria-label':'Nombre de hoja'});b.append(input);},[{label:'Cancelar',value:false},{label:'Crear',value:true,kind:'primary'}]);if(ok){const name=input.value.trim();if(!name||/[\\/?*\[\]:]/.test(name)||this.book.SheetNames.includes(name)){toast('Nombre de hoja no válido o repetido','warn');return;}this.X.utils.book_append_sheet(this.book,this.X.utils.aoa_to_sheet([['']]),name);this.sheet=name;this.start=0;this.refreshTabs();this.render();this.owner.changed();}}
  sort(){const ws=this.book.Sheets[this.sheet];if(Object.values(ws).some(c=>c?.f)){toast('Ordenar fórmulas puede cambiar referencias. Convierte primero el rango a valores.','warn');return;}const data=this.X.utils.sheet_to_json(ws,{header:1,defval:''}),col=this.X.utils.decode_cell(this.address).c,header=data.shift();data.sort((a,b)=>String(a[col]??'').localeCompare(String(b[col]??''),undefined,{numeric:true}));this.book.Sheets[this.sheet]=this.X.utils.aoa_to_sheet([header||[],...data]);this.render();this.owner.changed();}
}
