import {h,clear,dialog,downloadBlob,safeFileName,toast} from './dom.js';
const SVG='http://www.w3.org/2000/svg';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(+n)?+n:a));
export function cleanVector(data,w=512,h=512){
  const color=(v,f)=>v==='none'||/^#[a-f0-9]{6}$/i.test(v||'')?v:f;
  return {width:clamp(data?.width||w,1,8192),height:clamp(data?.height||h,1,8192),nodes:(Array.isArray(data?.nodes)?data.nodes:[]).slice(0,500).filter(n=>n&&['rect','ellipse','text','path'].includes(n.kind)).map(n=>({kind:n.kind,x:clamp(n.x,-16000,16000),y:clamp(n.y,-16000,16000),w:clamp(n.w,1,16000),h:clamp(n.h,1,16000),rotation:clamp(n.rotation,-360,360),fill:color(n.fill,'#7185f5'),stroke:color(n.stroke,'#1b1e2b'),line:clamp(n.line,0,100),opacity:clamp(n.opacity??1,0,1),size:clamp(n.size||32,4,1000),text:String(n.text||'Texto').slice(0,4000),closed:!!n.closed,smooth:!!n.smooth,points:(Array.isArray(n.points)?n.points:[]).slice(0,1000).filter(p=>Array.isArray(p)&&p.length===2).map(p=>[clamp(p[0],-16000,16000),clamp(p[1],-16000,16000)])}))};
}
function svg(tag,attrs={}){const n=document.createElementNS(SVG,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;}
function path(points,smooth,closed){if(!points.length)return '';let d='M '+points[0].join(' ');for(let i=1;i<points.length;i++){if(smooth){const a=points[i-2]||points[i-1],b=points[i-1],c=points[i],e=points[i+1]||c;d+=' C '+[b[0]+(c[0]-a[0])/6,b[1]+(c[1]-a[1])/6,c[0]-(e[0]-b[0])/6,c[1]-(e[1]-b[1])/6,c[0],c[1]].join(' ');}else d+=' L '+points[i].join(' ');}return d+(closed?' Z':'');}
function drawNode(n){const tag=n.kind==='path'?'path':n.kind==='text'?'text':n.kind;const el=svg(tag,{fill:n.fill,stroke:n.stroke,'stroke-width':n.line,opacity:n.opacity,transform:'translate('+n.x+' '+n.y+') rotate('+n.rotation+' '+n.w/2+' '+n.h/2+')','stroke-linejoin':'round','stroke-linecap':'round'});if(n.kind==='rect'){el.setAttribute('width',n.w);el.setAttribute('height',n.h);}if(n.kind==='ellipse'){el.setAttribute('cx',n.w/2);el.setAttribute('cy',n.h/2);el.setAttribute('rx',n.w/2);el.setAttribute('ry',n.h/2);}if(n.kind==='text'){el.setAttribute('font-size',n.size);el.setAttribute('font-family','Arial, sans-serif');el.setAttribute('y',n.size);n.text.split('\n').forEach((line,i)=>{const t=svg('tspan',{x:0,dy:i?'1.2em':0});t.textContent=line;el.append(t);});}if(n.kind==='path')el.setAttribute('d',path(n.points,n.smooth,n.closed));return el;}
export function vectorSVG(data){const d=cleanVector(data),root=svg('svg',{xmlns:SVG,width:d.width,height:d.height,viewBox:'0 0 '+d.width+' '+d.height});d.nodes.forEach(n=>root.append(drawNode(n)));return new XMLSerializer().serializeToString(root);}
export async function vectorDesigner(panel){
  const doc=panel.doc;if(!doc)return;let model=cleanVector(doc.vectorDraft,doc.w,doc.h),selected=-1,tool='move',history=[],future=[],root,stage,props,list,mode;
  const save=()=>{doc.vectorDraft=cleanVector(model);doc.dirty=true;panel.app.recovery?.schedule('art');};
  const checkpoint=()=>{history.push(JSON.stringify(model));if(history.length>40)history.shift();future=[];};
  const change=()=>{save();render();};
  const add=kind=>{checkpoint();model.nodes.push(cleanVector({nodes:[{kind,x:20,y:20,w:Math.min(160,model.width/2),h:Math.min(100,model.height/2),fill:kind==='path'?'none':panel.primary,stroke:panel.secondary,line:kind==='text'?0:2,size:Math.min(32,model.height/4),opacity:1,points:[]}]}).nodes[0]);selected=model.nodes.length-1;tool=kind==='path'?'pen':'move';change();};
  const pos=e=>{const r=root.getBoundingClientRect();return[(e.clientX-r.left)*model.width/r.width,(e.clientY-r.top)*model.height/r.height];};
  function render(){clear(stage);clear(list);root=svg('svg',{viewBox:'0 0 '+model.width+' '+model.height,'aria-label':'Lienzo vectorial',role:'img'});root.style.width='100%';root.style.maxHeight='55vh';root.style.aspectRatio=model.width+'/'+model.height;root.style.touchAction='none';stage.append(root);mode.textContent=tool==='pen'?'Pluma: haz clic para añadir puntos. Pulsa Mover al terminar.':'Mover: arrastra formas. Arrastra los puntos de un trazado para retocarlo.';
    root.onpointerdown=e=>{if(tool!=='pen'||e.button!==0)return;const n=model.nodes[selected];if(n?.kind!=='path')return;e.preventDefault();checkpoint();const p=pos(e);n.points.push([Math.round(p[0]-n.x),Math.round(p[1]-n.y)]);change();};
    model.nodes.forEach((n,i)=>{const el=drawNode(n);root.append(el);el.style.cursor=tool==='pen'?'crosshair':'move';if(i===selected){el.style.filter='drop-shadow(0px 0px 2px #6377ff)';}
      el.onpointerdown=e=>{if(tool==='pen'||e.button!==0)return;e.stopPropagation();e.preventDefault();checkpoint();selected=i;renderProps();const start=pos(e),x=n.x,y=n.y;el.setPointerCapture(e.pointerId);const move=ev=>{const p=pos(ev);n.x=Math.round(x+p[0]-start[0]);n.y=Math.round(y+p[1]-start[1]);el.setAttribute('transform','translate('+n.x+' '+n.y+') rotate('+n.rotation+' '+n.w/2+' '+n.h/2+')');};const done=()=>{el.removeEventListener('pointermove',move);change();};el.addEventListener('pointermove',move);el.addEventListener('pointerup',done,{once:true});el.addEventListener('pointercancel',()=>{n.x=x;n.y=y;done();},{once:true});};
      list.append(h('button.btn.small',{class:i===selected?'primary':null,on:{click:()=>{selected=i;tool='move';render();}}},(i+1)+' · '+({rect:'Rectángulo',ellipse:'Elipse',text:n.text.slice(0,18),path:'Trazado'}[n.kind])));
      if(i===selected&&n.kind==='path'&&tool!=='pen'&&n.rotation===0)for(let k=0;k<n.points.length;k++){const p=n.points[k],handle=svg('circle',{cx:p[0]+n.x,cy:p[1]+n.y,r:Math.max(model.width/140,1.5),fill:'#fff',stroke:'#6377ff','stroke-width':Math.max(model.width/500,.5)});root.append(handle);handle.style.cursor='crosshair';handle.onpointerdown=e=>{e.stopPropagation();e.preventDefault();checkpoint();handle.setPointerCapture(e.pointerId);const before=p.slice();const move=ev=>{const q=pos(ev);p[0]=Math.round(q[0]-n.x);p[1]=Math.round(q[1]-n.y);handle.setAttribute('cx',p[0]+n.x);handle.setAttribute('cy',p[1]+n.y);el.setAttribute('d',path(n.points,n.smooth,n.closed));};const end=()=>{handle.removeEventListener('pointermove',move);change();};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end,{once:true});handle.addEventListener('pointercancel',()=>{p.splice(0,2,...before);end();},{once:true});};}
    });renderProps();
  }
  function renderProps(){clear(props);const n=model.nodes[selected];if(!n){props.append(h('p.help','Crea una forma o selecciona un objeto.'));return;}
    for(const[key,label,min,max]of [['x','X',-16000,16000],['y','Y',-16000,16000],['w','Ancho',1,16000],['h','Alto',1,16000],['rotation','Rotación',-360,360],['line','Borde',0,100],['opacity','Opacidad',0,1]])props.append(h('label',label,h('input',{type:'number',value:n[key],min,max,step:key==='opacity'?.05:1,'aria-label':label+' vectorial',on:{change:e=>{checkpoint();n[key]=clamp(e.target.value,min,max);change();}}})));
    for(const[key,label]of [['fill','Relleno'],['stroke','Trazo']])props.append(h('label',label,h('input',{type:'color',value:n[key]==='none'?'#000000':n[key],'aria-label':label+' vectorial',on:{change:e=>{checkpoint();n[key]=e.target.value;change();}}}),h('button.btn.small',{on:{click:()=>{checkpoint();n[key]='none';change();}}},'Sin '+label.toLowerCase())));
    if(n.kind==='text'){props.append(h('textarea',{'aria-label':'Texto vectorial',value:n.text,on:{change:e=>{checkpoint();n.text=e.target.value.slice(0,4000);change();}}}),h('input',{type:'number',min:4,max:1000,value:n.size,'aria-label':'Tamaño vectorial',on:{change:e=>{checkpoint();n.size=clamp(e.target.value,4,1000);change();}}}));}
    if(n.kind==='path'){for(const[key,label]of [['closed','Cerrar trazado'],['smooth','Curva suave']])props.append(h('label.chk',h('input',{type:'checkbox',checked:n[key],on:{change:e=>{checkpoint();n[key]=e.target.checked;change();}}}),label));props.append(h('button.btn.small',{on:{click:()=>{checkpoint();n.points.pop();change();}}},'Quitar último punto'));}
    props.append(h('button.btn.small',{on:{click:()=>{checkpoint();model.nodes.push(structuredClone(n));selected=model.nodes.length-1;model.nodes[selected].x+=8;change();}}},'Duplicar'),h('button.btn.small',{on:{click:()=>{checkpoint();model.nodes.splice(selected,1);model.nodes.push(n);selected=model.nodes.length-1;change();}}},'Traer al frente'),h('button.btn.small',{on:{click:()=>{checkpoint();model.nodes.splice(selected,1);selected=-1;change();}}},'Borrar objeto'));
  }
  const action=await dialog('Diseño vectorial',body=>{
    const bar=h('div.office-tools');for(const[label,kind]of [['Rectángulo','rect'],['Elipse','ellipse'],['Texto','text'],['Pluma','path']])bar.append(h('button.btn.small',{on:{click:()=>add(kind)}},'＋ '+label));bar.append(h('button.btn.small',{on:{click:()=>{tool='move';render();}}},'Mover / puntos'),h('button.btn.small',{on:{click:()=>{if(history.length){future.push(JSON.stringify(model));model=JSON.parse(history.pop());selected=-1;change();}}}},'Deshacer'),h('button.btn.small',{on:{click:()=>{if(future.length){history.push(JSON.stringify(model));model=JSON.parse(future.pop());selected=-1;change();}}}},'Rehacer'),h('button.btn.small',{on:{click:()=>downloadBlob(new Blob([vectorSVG(model)],{type:'image/svg+xml'}),safeFileName(doc.name)+'.svg')}},'Descargar SVG'),h('button.btn.small',{on:{click:()=>downloadBlob(new Blob([JSON.stringify({format:'UltraGame Vector',version:1,...model})],{type:'application/json'}),safeFileName(doc.name)+'.ugvector')}},'Guardar editable'),h('button.btn.small',{on:{click:()=>{const input=h('input',{type:'file',accept:'.ugvector'});input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>4*1048576)throw Error('Diseño demasiado grande');const data=JSON.parse(await file.text());if(data.format!=='UltraGame Vector'||data.version!==1)throw Error('Formato no compatible');checkpoint();model=cleanVector(data);selected=-1;change();}catch(e){toast(e.message,'error');}};input.click();}}},'Abrir editable'));
    mode=h('p.help');stage=h('div.vector-stage');props=h('div.vector-props');list=h('div.office-tools');body.append(bar,mode,h('div.vector-layout',stage,props),list,h('p.help','El diseño se conserva en el archivo .ugart y en recuperación. SVG mantiene las formas; «Añadir como capa» crea píxeles para pintar encima.'));render();
  },[{label:'Cerrar',value:null},{label:'Añadir como capa',value:'layer',kind:'primary'}],true);
  save();if(action==='layer'){const image=new Image(),url=URL.createObjectURL(new Blob([vectorSVG(model)],{type:'image/svg+xml'}));try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('No se pudo dibujar el vector'));image.src=url;});panel.pasteImage(image,'Diseño vectorial');}finally{URL.revokeObjectURL(url);}}
}
