import {WordFile,PresentationFile,newWord,newPresentation,sheetLibrary,pdfLibrary,convertOffice,first,all,recalculate,zipLibrary} from '../js/office-core.js';
import {insertOfficeImage} from '../js/office-images.js';
import {DocumentsPanel} from '../js/documents.js';
const results=document.getElementById('results'),host=document.getElementById('fixture');let passed=0,failed=0;
const assert=(v,s)=>{if(!v)throw Error(s);};
async function test(name,fn){const p=document.createElement('p');try{await fn();passed++;p.textContent='✓ '+name;}catch(e){failed++;p.textContent='✗ '+name+': '+e.message;p.style.color='#f88';}results.append(p);document.getElementById('summary').textContent=passed+' correctas, '+failed+' fallidas';}
const app={selectTab(){},layout:{toggleFocus(){}},recovery:{schedule(){},async capture(){}}};const panel=new DocumentsPanel(app,host);let wordBytes,slideBytes,bookBytes;
await test('DOCX: texto, formato y tabla sobreviven guardar y abrir',async()=>{const word=await WordFile.open(await newWord()),p=first(word.body,'p');word.setParagraph(p,[{text:'Árbol de pruebas',bold:true,italic:true,underline:true,strike:true,color:'#aabbcc',size:20}],'center');word.addTable(2,3);wordBytes=await word.bytes();const loaded=await WordFile.open(wordBytes);assert(first(loaded.xml,'t').textContent==='Árbol de pruebas','texto');assert(all(loaded.xml,'tc').length===6&&first(loaded.xml,'strike'),'tabla o tachado');});
await test('DOCX: imagen incrustada, sin URL externa',async()=>{const c=document.createElement('canvas');c.width=c.height=10;c.getContext('2d').fillRect(0,0,10,10);const file=new File([await new Promise(r=>c.toBlob(r))],'imagen.png',{type:'image/png'}),w=await WordFile.open(wordBytes);await insertOfficeImage(w,file);wordBytes=await w.bytes();const opened=await WordFile.open(wordBytes);assert(opened.images.size===1&&all(opened.xml,'drawing').length===1,'imagen perdida');});
await test('Interfaz de texto guarda contenido editado',async()=>{await panel.loadBytes(wordBytes,'docx','Prueba.docx');const p=host.querySelector('[contenteditable]');p.textContent='Texto modificado desde el editor';p.dispatchEvent(new Event('input',{bubbles:true}));const reread=await WordFile.open(await panel.bytes());assert(first(reread.xml,'t').textContent==='Texto modificado desde el editor','no guardó');});
await test('Deshacer y rehacer en Documentos',async()=>{await panel.checkpoint();await panel.undo(false);assert(host.querySelector('[contenteditable]').textContent==='Árbol de pruebas','no deshizo');await panel.undo(true);assert(host.querySelector('[contenteditable]').textContent==='Texto modificado desde el editor','no rehizo');});
await test('XLSX y XLS: celdas, fórmulas y varias hojas',async()=>{const X=await sheetLibrary(),book=X.utils.book_new();X.utils.book_append_sheet(book,X.utils.aoa_to_sheet([[2,3,{t:'n',f:'A1+B1',v:0}],[8,7,{t:'n',f:'SUM(A1:B2)',v:0}]]),'Datos');X.utils.book_append_sheet(book,X.utils.aoa_to_sheet([['Segunda']]),'Notas');assert(recalculate(book,X).length===0&&book.Sheets.Datos.C2.v===20,'cálculo');for(const bookType of ['xlsx','xls']){const bytes=X.write(book,{type:'array',bookType}),loaded=X.read(bytes,{type:'array',cellNF:true});assert(loaded.Sheets.Datos.C1.f==='A1+B1'&&loaded.SheetNames.length===2,'fórmula u hojas');if(bookType==='xlsx')bookBytes=new Uint8Array(bytes);}});
await test('CSV: comas, comillas, Unicode y saltos de línea',async()=>{const X=await sheetLibrary(),ws=X.utils.aoa_to_sheet([['café, té','una "cita"','dos\nlíneas']]),csv=X.utils.sheet_to_csv(ws),w=X.read(csv,{type:'string'});assert(w.Sheets[w.SheetNames[0]].C1.v==='dos\nlíneas','salto perdido');});
await test('Hojas: edición recalcula dependientes y conserva formato',async()=>{await panel.loadBytes(bookBytes,'xlsx','Prueba.xlsx');panel.widget.setCell('A1','10');assert(panel.current.model.Sheets.Datos.C1.v===13,'valor dependiente');const cell=panel.current.model.Sheets.Datos.A1;cell.z='0.00';panel.widget.setCell('A1','12');assert(cell!==panel.current.model.Sheets.Datos.A1&&panel.current.model.Sheets.Datos.A1.z==='0.00','formato perdido');});
await test('Fórmulas: ciclos y código no ejecutable',async()=>{const X=await sheetLibrary(),b={SheetNames:['S'],Sheets:{S:{A1:{f:'B1',t:'n',v:0},B1:{f:'A1',t:'n',v:0},C1:{f:'alert(1)',v:99,t:'n'}}}};const errors=recalculate(b,X);assert(errors.length===3&&b.Sheets.S.C1.f==='alert(1)','no se rechazó');});
await test('PPTX: texto, geometría e imagen; duplicar diapositiva',async()=>{const p=await PresentationFile.open(await newPresentation()),shape=p.addShape(0);p.setText(shape,'Presentación de prueba');p.setBounds(shape,{x:25,y:40,w:400,h:110});const c=document.createElement('canvas');c.width=c.height=8;await insertOfficeImage(p,new File([await new Promise(r=>c.toBlob(r))],'test.png',{type:'image/png'}),0);await p.duplicateSlide(0);slideBytes=await p.bytes();const q=await PresentationFile.open(slideBytes);assert(q.slides.length===2&&q.slides[1].images.size===1,'copia o imagen');assert(q.bounds(q.shapes(1)[0]).x===25&&all(q.shapes(0)[0],'t')[0].textContent==='Presentación de prueba','propiedades');});
await test('PDF: texto, página, formulario y anotación conservados',async()=>{const P=await pdfLibrary(),pdf=await P.PDFDocument.create();pdf.addPage([400,500]).drawText('Prueba original');pdf.getForm().createTextField('nombre').addToPage(pdf.getPage(0));pdf.getForm().getTextField('nombre').setText('Ana');await panel.loadBytes(await pdf.save(),'pdf','Prueba.pdf');await panel.widget.ready;assert(host.querySelector('canvas')?.width>0,'no renderizó PDF');panel.widget.tool='highlight';await panel.widget.annotate([10,50],[120,70],[]);const opened=await P.PDFDocument.load(await panel.bytes());assert(opened.getPageCount()===1&&opened.getForm().getTextField('nombre').getText()==='Ana','PDF dañado');});
await test('Recuperación .ugdoc abre el documento completo',async()=>{const snapshot=await panel.snapshot();panel.current.dirty=false;await panel.restore(snapshot,{name:'Copia',key:'qa-document'});assert(panel.current.type==='pdf'&&panel.current.recoveryKey==='qa-document','recuperación');await panel.widget.ready;panel.current.dirty=false;});
await test('Rechaza copia manipulada y XML con entidades',async()=>{const Z=await zipLibrary(),z=new Z();z.file('word/document.xml','<!DOCTYPE x [<!ENTITY y SYSTEM "file:///c:/secret">]><w:document/>');let rejected=false;try{await WordFile.open(await z.generateAsync({type:'uint8array'}));}catch{rejected=true;}assert(rejected,'aceptó entidad');});
let converter;try{converter=await(await fetch('/api/office',{headers:{'X-UG-Studio':'1'}})).json();}catch{}
if(converter?.available){for(const ext of ['doc','rtf','pdf'])await test('Conversión DOCX → '+ext.toUpperCase()+(ext!=='pdf'?' → DOCX':''),async()=>{const out=await convertOffice(wordBytes,'docx',ext);assert(out.length>100,'archivo vacío');if(ext!=='pdf'){const read=await WordFile.open(await convertOffice(out,ext,'docx'));assert(all(read.xml,'t').some(t=>t.textContent.includes('Árbol')),'contenido perdido');}else{const P=await pdfLibrary();assert((await P.PDFDocument.load(out)).getPageCount()>0,'PDF vacío');}});
await test('Conversión PPTX → PDF',async()=>{const P=await pdfLibrary(),pdf=await P.PDFDocument.load(await convertOffice(slideBytes,'pptx','pdf'));assert(pdf.getPageCount()===2,'faltan diapositivas');});
await test('Conversión XLSX → PDF',async()=>{const P=await pdfLibrary(),pdf=await P.PDFDocument.load(await convertOffice(bookBytes,'xlsx','pdf'));assert(pdf.getPageCount()>=2,'faltan hojas');});}else {const p=document.createElement('p');p.textContent='Conversión local no probada: abre con el servidor Studio autenticado y LibreOffice instalado.';results.append(p);}
clearTimeout(panel.historyTimer);document.getElementById('summary').dataset.done='true';
